pipeline {
    agent any

//     stages {
//         stage('CleanWorkspace') {
//             steps {
//                 cleanWs()
//             }
//         }

        stage('CI') {
            steps {
                git url: 'https://github.com/paulahakeem/jenkins_nodejs_example.git'
                withCredentials([usernamePassword(credentialsId: 'DOCKERHUB', passwordVariable: 'my_pass', usernameVariable: 'my_user')]) {
                    sh """
                    docker login -u ${my_user} -p ${my_pass}
                    docker build . -f Dockerfile -t paulahakeem/iti:v1.0
                    docker push paulahakeem/iti:v1.0
                    """
                }
            }
        }

        stage('CD') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKERHUB', passwordVariable: 'my_pass', usernameVariable: 'my_user')]) {
                    sh """
                    docker login -u ${my_user} -p ${my_pass}
                    docker run -d -p 3001:3000 paulahakeem/iti:v1.0
                    """
                }
            }
        }
    }
}
